name: Build and Deploy # Name of the workflow

on:
  push: # Trigger the workflow on push events
    branches:
      - master # Only trigger on the main branch

jobs:
  build: # Name of the job
    runs-on: ubuntu-latest # Use the latest version of Ubuntu as the runner

    steps: # Steps to be executed in the job
    - name: Checkout repository # Checkout the repository
      uses: actions/checkout@v2 # Use the actions/checkout action

    - name: Install dependencies # Install project dependencies
      run: npm install --force # Run the npm install command

    - name: Build # Build the project
      run: npm run build # Run the npm run build command
    
    - name: Prepare build dir
      run: |
        mkdir cloned-repo
        git clone https://github.com/KingerNL/cv cloned-repo
        cd cloned-repo
        shopt -s extglob
        rm -rf !(.git) # Remove all files and folders except .git
    
    - name: Commit and push changes
      run: |
        cd cloned-repo
        git add -A
        git commit -m "Update build artifacts"
        git push origin main